"""
Keyword-overlap retrieval for RAG chunks (no GPU, no extra dependencies).

Chunks are loaded from data/rag_index/chunks.jsonl (generated by ingest.py).
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

log = logging.getLogger(__name__)

# Boost retrieval when the user's goal matches chunk topic.
GOAL_KEYWORDS: dict[str, str] = {
    "financial_foundations": "emergency fund savings goals net worth budgeting basics financial habits",
    "budget_cashflow": "budget income expenses cash flow fixed variable 50 30 20 tracking",
    "credit_management": "credit score APR utilization minimum payment revolving debt report",
    "workplace_401k": "401k employer match contribution vesting retirement salary deferral",
    "student_loans": "student loan federal private repayment IDR principal interest forgiveness",
    "borrowing_basics": "loan interest amortization secured unsecured debt to income borrowing",
}


def _tokenize(text: str) -> set[str]:
    return set(re.findall(r"[a-z0-9]+", text.lower()))


def _score(query_tokens: set[str], text: str) -> float:
    doc_tokens = _tokenize(text)
    if not query_tokens or not doc_tokens:
        return 0.0
    overlap = query_tokens & doc_tokens
    # Jaccard-like balance: overlap / query size (prioritize matching user's query terms)
    return len(overlap) / max(1, len(query_tokens))


class RAGRetriever:
    """Loads chunks once; retrieves top-k by keyword overlap with a built query."""

    def __init__(self, chunks_path: Path | None):
        self.chunks_path = chunks_path
        self._chunks: list[dict] = []
        if chunks_path and chunks_path.is_file():
            self._load()
        elif chunks_path:
            log.warning("RAG chunks file not found: %s — RAG disabled.", chunks_path)

    def _load(self) -> None:
        with open(self.chunks_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    self._chunks.append(json.loads(line))
                except json.JSONDecodeError as e:
                    log.warning("Skipping bad JSONL line: %s", e)

        log.info("Loaded %d RAG chunks from %s", len(self._chunks), self.chunks_path)

    @property
    def enabled(self) -> bool:
        return bool(self._chunks)

    def build_query(self, primary_goal: str | None) -> str:
        g = primary_goal or "financial_foundations"
        extra = GOAL_KEYWORDS.get(g, "")
        return f"{g.replace('_', ' ')} {extra} educational overview key concepts checklist"

    def retrieve(self, query: str, k: int = 5, topic_filter: str | None = None) -> list[dict]:
        """
        Return top-k chunks using keyword overlap.

        Improvement vs. earlier version:
        - Prefer chunks whose `topic` matches `topic_filter` (topic-only ranking first).
        - If fewer than k chunks match the topic, backfill from other topics.
        - Avoid injecting clearly irrelevant chunks when overlap scores are all zero.
        """
        if not self._chunks:
            return []

        query_tokens = _tokenize(query)

        def rank(candidates: list[dict], topic_bonus: bool) -> list[tuple[float, dict]]:
            scored: list[tuple[float, dict]] = []
            for ch in candidates:
                text = ch.get("text", "")
                base = _score(query_tokens, text + " " + ch.get("heading", ""))
                if topic_bonus:
                    base += 0.35
                scored.append((base, ch))
            scored.sort(key=lambda x: x[0], reverse=True)
            return scored

        if topic_filter:
            topic_candidates = [ch for ch in self._chunks if ch.get("topic", "") == topic_filter]
            other_candidates = [ch for ch in self._chunks if ch.get("topic", "") != topic_filter]
        else:
            topic_candidates = self._chunks
            other_candidates = []

        out: list[dict] = []
        seen_ids: set[str] = set()

        def take_from_ranked(ranked: list[tuple[float, dict]], limit: int) -> None:
            nonlocal out
            nonlocal seen_ids

            # If we have any positive-overlap chunks, only take from them.
            positive = [t for t in ranked if t[0] > 0]
            source = positive if positive else ranked

            for score, ch in source:
                cid = ch.get("id", "")
                if cid in seen_ids:
                    continue
                seen_ids.add(cid)
                out.append(ch)
                if len(out) >= limit:
                    break

        ranked_topic = rank(topic_candidates, topic_bonus=bool(topic_filter))
        take_from_ranked(ranked_topic, k)

        if len(out) < k and other_candidates:
            ranked_other = rank(other_candidates, topic_bonus=False)
            take_from_ranked(ranked_other, k)

        return out[:k]

    def retrieve_for_state(self, state, k: int = 5) -> list[dict]:
        """Convenience: use goal from ChatbotState."""
        goal = getattr(getattr(state, "goal", None), "primary_goal", None)
        q = self.build_query(goal)
        return self.retrieve(q, k=k, topic_filter=goal)
